openapi: 3.1.0
info:
    version: 1.0.0
    title: Water App
    license:
        name: Apache 2.0
        url: http://www.apache.org/licenses/LICENSE-2.0.html
    description: This is a documentation for Water app
tags:
    - name: Authentication
      description: Authentication operations
    - name: User
      description: User profile operations
    - name: Water info
      description: Water operations
servers:
    - url: https://aqua-server-83k1.onrender.com
    - url: http://localhost:8080
paths:
    /auth/signup:
        post:
            $ref: ../swagger/paths/auth/signup.yaml
    /auth/signin:
        post:
            $ref: ../swagger/paths/auth/signin.yaml
    /auth/logout:
        post:
            $ref: ../swagger/paths/auth/logout.yaml
    /auth/request-reset-password:
        post:
            $ref: ../swagger/paths/auth/request-reset.yaml
    /auth/reset-password:
        post:
            $ref: ../swagger/paths/auth/reset-password.yaml
    /users/profile:
        get:
            $ref: ../swagger/paths/user/get.yaml
    /users/update:
        patch:
            $ref: ../swagger/paths/user/patch.yaml
    /users/happy:
        get:
            $ref: ../swagger/paths/user/getHappy.yaml
    /water:
        post:
            $ref: ../swagger/paths/water/post.yaml
    /water/{id}:
        patch:
            $ref: ../swagger/paths/water/{id}/patch.yaml
        delete:
            $ref: ../swagger/paths/water/{id}/delete.yaml
    /water/daily/{date}:
        get:
            $ref: ../swagger/paths/water/{date}/get.yaml
    /water/monthly/{year}/{month}:
        get:
            $ref: ../swagger/paths/water/{month}/get.yaml

components:
    securitySchemes:
        bearerAuth:
            type: http
            scheme: bearer
